-- +migrate Up

-- MySQL Script generated by MySQL Workbench
-- Čt 30. březen 2017, 20:13:23 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id`  INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL UNIQUE,
  `hash` BINARY(20) NOT NULL,
  `salt` CHAR(8) NOT NULL);


-- -----------------------------------------------------
-- Table `currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `currencies` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `code` VARCHAR(6) NOT NULL UNIQUE,
  `name` VARCHAR(45) NOT NULL);


-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `countries` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(45) NOT NULL);


-- -----------------------------------------------------
-- Table `currency_pairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `currency_pairs` (
  `date` DATETIME NOT NULL,
  `src_currency_id` INT NOT NULL,
  `dst_currency_id` INT NOT NULL,
  `multiplier` DOUBLE NOT NULL,
  PRIMARY KEY (`date`, `src_currency_id`, `dst_currency_id`),
  CONSTRAINT `fk_currency_pairs_1`
    FOREIGN KEY (`src_currency_id` , `dst_currency_id`)
    REFERENCES `currencies` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `portfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolios` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `owner_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
 --PRIMARY KEY (`id`),
  --INDEX `fk_portfolios_1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_portfolios_1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `markets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `markets` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `default_currency_id` INT NULL,
  `default_country_id` INT NULL,
  --PRIMARY KEY (`id`),
  --INDEX `fk_markets_1_idx` (`default_currency_id` ASC),
  --INDEX `fk_markets_2_idx` (`default_country_id` ASC),
  CONSTRAINT `fk_markets_1`
    FOREIGN KEY (`default_currency_id`)
    REFERENCES `currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_markets_2`
    FOREIGN KEY (`default_country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `items` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `market_id` INT NOT NULL,
  `currency_id` INT NULL,
  `country_id` INT NULL,
  `code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(256) NULL,
  `address` VARCHAR(256) NULL,
  --PRIMARY KEY (`id`),
  --INDEX `fk_items_1_idx` (`market_id` ASC),
  --INDEX `fk_items_2_idx` (`currency_id` ASC),
  --INDEX `fk_items_3_idx` (`country_id` ASC),
  CONSTRAINT `fk_items_1`
    FOREIGN KEY (`market_id`)
    REFERENCES `markets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_2`
    FOREIGN KEY (`currency_id`)
    REFERENCES `currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_3`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `portfolio_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_items` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `portfolio_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `_amount_sum` DOUBLE NULL,
  `_buy_price_avg` DOUBLE NULL,
  `_fee_sum` DOUBLE NULL,
  --INDEX `fk_portfolio_items_2_idx` (`item_id` ASC),
  CONSTRAINT `fk_portfolio_items_1`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `portfolios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portfolio_items_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `item_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `item_prices` (
  `date` DATETIME NOT NULL,
  `item_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`date`, `item_id`),
  --INDEX `fk_item_prices_1_idx` (`item_id` ASC),
  CONSTRAINT `fk_item_prices_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `portfolio_item_adds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_item_adds` (
  `portfolio_item_id` INT NOT NULL,
  PRIMARY KEY (`portfolio_item_id`),
  CONSTRAINT `fk_portfolio_item_adds_1`
    FOREIGN KEY (`portfolio_item_id`)
    REFERENCES `portfolio_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `portfolio_item_removes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_item_removes` (
  `portfolio_item_id` INT NOT NULL,
  PRIMARY KEY (`portfolio_item_id`),
  CONSTRAINT `fk_portfolio_item_removes_1`
    FOREIGN KEY (`portfolio_item_id`)
    REFERENCES `portfolio_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- +migrate Down
DROP TABLE IF EXISTS `users` ;
DROP TABLE IF EXISTS `currencies` ;
DROP TABLE IF EXISTS `countries` ;
DROP TABLE IF EXISTS `currency_pairs` ;
DROP TABLE IF EXISTS `portfolios` ;
DROP TABLE IF EXISTS `markets` ;
DROP TABLE IF EXISTS `items` ;
DROP TABLE IF EXISTS `portfolio_items` ;
DROP TABLE IF EXISTS `item_prices` ;
DROP TABLE IF EXISTS `portfolio_item_adds` ;
DROP TABLE IF EXISTS `portfolio_item_removes` ;


